import 'models.dart';

final List<Organization> mockOrganizations = [
  Organization(
    id: '1',
    name: 'Tech Academy',
    description: 'Leading provider of technology courses and certifications',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 45,
    categories: ['Technology'],
  ),
  Organization(
    id: '2',
    name: 'Business Institute',
    description: 'Professional business training and development programs',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 32,
    categories: ['Business'],
  ),
  Organization(
    id: '3',
    name: 'Creative Arts Center',
    description: 'Unleash your creativity with our comprehensive arts programs',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 28,
    categories: ['Arts'],
  ),
  Organization(
    id: '4',
    name: 'Medical Training Hub',
    description: 'Advanced medical education and healthcare training',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 38,
    categories: ['Healthcare'],
  ),
  Organization(
    id: '5',
    name: 'Science Academy',
    description: 'Explore the wonders of science with our expert-led courses',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 22,
    categories: ['Science'],
  ),
];

List<Course> mockCourses = [
  Course(
    id: '1',
    organizationId: '1',
    title: 'Introduction to Programming',
    description: 'Learn the fundamentals of programming with hands-on projects',
    instructor: 'Dr. Sarah Johnson',
    duration: const Duration(hours: 40),
    level: 'Beginner',
    rating: 4.8,
    enrolledStudents: 1250,
  ),
  Course(
    id: '2',
    organizationId: '1',
    title: 'Advanced Data Structures',
    description: 'Master complex data structures and algorithms',
    instructor: 'Prof. Michael Chen',
    duration: const Duration(hours: 60),
    level: 'Advanced',
    rating: 4.9,
    enrolledStudents: 890,
  ),
  Course(
    id: '3',
    organizationId: '1',
    title: 'Web Development Fundamentals',
    description: 'Build modern web applications from scratch',
    instructor: 'Jessica Martinez',
    duration: const Duration(hours: 50),
    level: 'Intermediate',
    rating: 4.7,
    enrolledStudents: 2100,
  ),
  Course(
    id: '4',
    organizationId: '1',
    title: 'Mobile App Development',
    description: 'Create cross-platform mobile applications',
    instructor: 'David Kim',
    duration: const Duration(hours: 45),
    level: 'Intermediate',
    rating: 4.6,
    enrolledStudents: 1680,
  ),
  Course(
    id: '5',
    organizationId: '1',
    title: 'Machine Learning Basics',
    description: 'Introduction to AI and machine learning concepts',
    instructor: 'Dr. Emily Watson',
    duration: const Duration(hours: 35),
    level: 'Beginner',
    rating: 4.8,
    enrolledStudents: 950,
  ),
  // Business Institute Courses
  Course(
    id: '6',
    organizationId: '2',
    title: 'Business Analytics',
    description: 'Analyze business data for better decision making',
    instructor: 'Dr. Alan Smith',
    duration: const Duration(hours: 30),
    level: 'Intermediate',
    rating: 4.5,
    enrolledStudents: 700,
  ),
  Course(
    id: '7',
    organizationId: '2',
    title: 'Financial Management',
    description: 'Master the essentials of financial management',
    instructor: 'Prof. Linda Green',
    duration: const Duration(hours: 40),
    level: 'Beginner',
    rating: 4.6,
    enrolledStudents: 800,
  ),
  // Creative Arts Center Courses
  Course(
    id: '8',
    organizationId: '3',
    title: 'Digital Painting',
    description: 'Create stunning digital art with modern tools',
    instructor: 'Emily Brown',
    duration: const Duration(hours: 25),
    level: 'Beginner',
    rating: 4.7,
    enrolledStudents: 500,
  ),
  Course(
    id: '9',
    organizationId: '3',
    title: 'Photography Masterclass',
    description: 'Become a pro photographer',
    instructor: 'Michael Lee',
    duration: const Duration(hours: 35),
    level: 'Intermediate',
    rating: 4.8,
    enrolledStudents: 600,
  ),
  // Medical Training Hub Courses
  Course(
    id: '10',
    organizationId: '4',
    title: 'First Aid Essentials',
    description: 'Learn life-saving first aid skills',
    instructor: 'Dr. Susan White',
    duration: const Duration(hours: 20),
    level: 'Beginner',
    rating: 4.9,
    enrolledStudents: 900,
  ),
  Course(
    id: '11',
    organizationId: '4',
    title: 'Advanced Nursing',
    description: 'Deep dive into advanced nursing practices',
    instructor: 'Nurse John Carter',
    duration: const Duration(hours: 50),
    level: 'Advanced',
    rating: 4.8,
    enrolledStudents: 400,
  ),
  // Science Academy Courses
  Course(
    id: '12',
    organizationId: '5',
    title: 'Quantum Physics',
    description: 'Explore the mysteries of quantum mechanics',
    instructor: 'Dr. Albert Newton',
    duration: const Duration(hours: 60),
    level: 'Advanced',
    rating: 4.9,
    enrolledStudents: 300,
  ),
  Course(
    id: '13',
    organizationId: '5',
    title: 'Biology Basics',
    description: 'Understand the fundamentals of biology',
    instructor: 'Dr. Lisa Darwin',
    duration: const Duration(hours: 30),
    level: 'Beginner',
    rating: 4.7,
    enrolledStudents: 650,
  ),
];
