import 'models.dart';

final List<Organization> mockOrganizations = [
  Organization(
    id: '1',
    name: 'Tech Academy',
    description: 'Leading provider of technology courses and certifications',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 45,
    categories: ['Technology'],
  ),
  Organization(
    id: '2',
    name: 'Business Institute',
    description: 'Professional business training and development programs',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 32,
    categories: ['Business'],
  ),
  Organization(
    id: '3',
    name: 'Creative Arts Center',
    description: 'Unleash your creativity with our comprehensive arts programs',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 28,
    categories: ['Arts'],
  ),
  Organization(
    id: '4',
    name: 'Medical Training Hub',
    description: 'Advanced medical education and healthcare training',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 38,
    categories: ['Healthcare'],
  ),
  Organization(
    id: '5',
    name: 'Science Academy',
    description: 'Explore the wonders of science with our expert-led courses',
    imageUrl: 'https://via.placeholder.com/150',
    courseCount: 22,
    categories: ['Science'],
  ),
];

List<Course> mockCourses = [
  Course(
    id: '1',
    title: 'Introduction to Programming',
    description: 'Learn the fundamentals of programming with hands-on projects',
    instructor: 'Dr. Sarah Johnson',
    duration: const Duration(hours: 40),
    level: 'Beginner',
    rating: 4.8,
    enrolledStudents: 1250,
  ),
  Course(
    id: '2',
    title: 'Advanced Data Structures',
    description: 'Master complex data structures and algorithms',
    instructor: 'Prof. Michael Chen',
    duration: const Duration(hours: 60),
    level: 'Advanced',
    rating: 4.9,
    enrolledStudents: 890,
  ),
  Course(
    id: '3',
    title: 'Web Development Fundamentals',
    description: 'Build modern web applications from scratch',
    instructor: 'Jessica Martinez',
    duration: const Duration(hours: 50),
    level: 'Intermediate',
    rating: 4.7,
    enrolledStudents: 2100,
  ),
  Course(
    id: '4',
    title: 'Mobile App Development',
    description: 'Create cross-platform mobile applications',
    instructor: 'David Kim',
    duration: const Duration(hours: 45),
    level: 'Intermediate',
    rating: 4.6,
    enrolledStudents: 1680,
  ),
  Course(
    id: '5',
    title: 'Machine Learning Basics',
    description: 'Introduction to AI and machine learning concepts',
    instructor: 'Dr. Emily Watson',
    duration: const Duration(hours: 35),
    level: 'Beginner',
    rating: 4.8,
    enrolledStudents: 950,
  ),
];
